### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Bunchy88** [HessiJames/mkv-bash-tools#1]
Hello, I have a small problem with your mkv-remove-language script.
If I try the batch command, I get the message: find: mkv-remove-language No such file or directory. The single command works perfectly.
hope you can help me

**Comment by dfaust** [comment]
You have two options:

1. Copy `mkv-remove-language` into a directory that's listed in your `$PATH` variable.

or

2. Copy `mkv-remove-language` into the directory with your .mkv files and run `find -iname "*" -exec ./mkv-transcode-flac '{}' \;`
Notice the relative path starting with `./`.

**Comment by Bunchy88** [comment]
thank you is run perfectly
